# Generated by Django 5.2.6 on 2025-09-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "PENDING"), ("PAID", "PAID")],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("PAYMENT", "PAYMENT"), ("FINE", "FINE")],
                        db_index=True,
                        default="PAYMENT",
                        max_length=10,
                    ),
                ),
                ("borrowing_id", models.PositiveIntegerField(db_index=True)),
                (
                    "session_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "money_to_pay",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "db_table": "payment",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("money_to_pay__gte", 0)),
                        name="money_to_pay_non_negative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("borrowing_id", "payment_type"),
                        name="uniq_pending_payment_per_borrowing_type_tmp",
                    ),
                ],
            },
        ),
    ]
