# Generated by Django 5.2.6 on 2025-09-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="uniq_pending_payment_per_borrowing_type_tmp",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="borrowing_id",
        ),
        migrations.AddField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="borrowings.borrowing",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("borrowing", "payment_type"),
                name="uniq_pending_payment_per_borrowing_type",
            ),
        ),
    ]
