# Generated by Django 5.2.6 on 2025-09-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
        (
            "payments",
            "0002_remove_payment_uniq_pending_payment_per_borrowing_type_tmp_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowings.borrowing",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PAID", "PAID"),
                    ("CANCELLED", "CANCELLED"),
                    ("EXCEEDED", "EXCEEDED"),
                    ("FAILED", "FAILED"),
                ],
                db_index=True,
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
