# Generated by Django 5.2.6 on 2025-09-22 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(
                help_text="The author of the book.", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                help_text="The cover type of the book (Hardcover or Softcover).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The daily fee for renting this book.",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(
                help_text="The number of books available in inventory."
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                help_text="The title of the book.", max_length=256
            ),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "author", "cover")},
        ),
    ]
