# Generated by Django 5.2.6 on 2025-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_author_alter_book_cover_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
    ]
