# Generated by Django 5.2.6 on 2025-09-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="borrowing",
            table="borrowings",
        ),
    ]
